### ISSUE TITLE
LinkedIn extrafields XML posts tag

### ISSUE THREAD

**Issue by kaitlyntier** [oneworldmarket/idibu-api#10]
Hi

I have the following XML for adding a job to LinkedIn with it's required extrafields included:
```
<?xml version="1.0" encoding="UTF-8"?>
<idibu>
  <method>add</method>
  <config>
    ...
  </config>
  <job id="">
    ...
    <posts>
      <board id="1599">
        <extrafield name="newlinkedin_share">No</extrafield>
        <extrafield name="newlinkedin_comp">-1</extrafield>
      </board>
    </posts>
  </job>
</idibu>
```

When I checked the required extrafields for LinkedIn, there are _newlinkedin_share_ and _newlinkedin_comp_. On my logs, I got an error
> Field 'newlinkedin_comp' was not supplied, or was supplied with an option that is an empty string or contains only whitespace.

What seems to be the problem? Have I used an invalid value for _newlinkedin_comp_?

**Comment by idibuseba** [comment]
Hey @kaitlyntier, the `newlinkedin_comp` field is actually a multi-select dropdown so, in order to send this data properly, you need to do it this way:
```
<extrafield name="newlinkedin_comp">
  <item id="-1" />
</extrafield>
```
As a matter of fact, this field is normally non-required (unless you change it to be required for the account) and can be ignored unless you want to dynamically obtain all the IDs of Company Walls to which a given profile is allowed to post.

To be able to do this, you need to use:
http://ws.idibu.com/clients/json.php?class=Portal&action=showData&boardID=1599&format=XML&hash=[HASH]&profileID=[USER-ID]
(so you don't only use hash in this case but also the ID of user's profile that is posting), and, of course,  that user needs to be properly connected to LinkedIn (proper token entered in `newlinkedin_token`). This way, the field will show all company pages's IDs where this user is allowed to post - otherwise you'll just always see `-1` as the only available option.

It's possible that this functionality will soon be removed as LinkedIn is undergoing API changes.
