### ISSUE TITLE
Seek board subscription

### ISSUE THREAD

**Issue by markzsanantonio** [oneworldmarket/idibu-api#11]
Hi

Everything was working properly with Seek board subscription until I tried updating Seek advertiser ID today and updating Seek subscription via post request to _http://ws.idibu.com/ws/rest/v1/portals/338/subscribe?hash=<my_hash>_. I got a failed response with a message **Specified column "postingDurationOptions" is not in the row**. I have checked the repository and fields required in subscribing to Seek board and there seem to be nothing related to that column or error. Posting duration for Seek only have 0 and 30 as it's options which in my case 30 was the selected duration which should be a valid option. The subscription worked after I commented out the posting duration XML field but I would still like to know what causes the message.

Thanks!

**Comment by idibuseba** [comment]
Hey @markzsanantonio are you able to provide the full XML that cause the error and the one that worked OK?

**Comment by markzsanantonio** [comment]
Hi @idibuseba 

Apologies for the late response. This is the full XML
```
<?xml version="1.0" encoding="UTF-8"?>
<request>
    <fields>
        <field>
            <name>PostDuration</name>
            <value>28</value>
        </field>
    </fields>
</request>
```


After sending the request it gave me this result
```
<?xml version="1.0" encoding="UTF-8"?>
<idibu generator="idibu" version="1.0">
    <response>
        <message>Specified column "postingDurationOptions" is not in the row</message>
    </response>
    <status>failed</status>
</idibu>
```

**Comment by idibuseba** [comment]
Hey @markzsanantonio, thanks for this!

When using the subscribe method, you can only specify the portal's specific extra fields. In order to update PostDuration, you'll need to use https://github.com/oneworldmarket/idibu-api/blob/master/webservices/portal-management/portal-additional-options/view-or-update-additional-options.md

I realize it's confusing, as when using GET with the subscribe method, you'll always get PostDuration too - it's a bug that we will work on fixing in future. Essentially, right now you can assume that the subscribe method allows controlling "everything it returns - except for the PostDuration field".

**Comment by markzsanantonio** [comment]
Thanks @idibuseba , I appreciate the response.
